### ISSUE TITLE
lambda & proc are assumed to be attributes

### ISSUE THREAD

**Issue by tadiou** [thoughtbot/factory_bot#1023]
https://github.com/tadiou/lambda_factory_girl is an example setup for this case.

I was rubocopping some old files in a factory, and it suggested I changed Proc.new to proc (based on 1.8 -> 1.9 changes), that failed because FG assumed proc was an attribute being assigned to a value. Same with `lambda` or `throw` or other general ruby keywords all get assumed to be attributes before they're recognized as core ruby syntax.

The functionality works fine, when I convert to `->` vs `lambda`, or if i pull it out of the factory block and put it in the same file as a method, but the DSL tries to read it and says nope.

**Comment by composerinteralia** [comment]
`self` where you are trying to define the `Proc` is an instance of `FactoryGirl::DefinitionProxy`:

```rb
FactoryGirl.define do
  factory :user do
    # Factory girl uses `instance_eval` to evaluate this block
    # in the context of a `FactoryGirl::DefinitionProxy` instance
  end
end
```

`FactoryGirl::DefinitionProxy` undefines all but a handful of [whitelisted methods](https://github.com/thoughtbot/factory_girl/blob/master/lib/factory_girl/definition_proxy.rb#L3), and neither `proc` or `lambda` make the cut. Undefining these methods keeps them from conflicting with attributes on the class you are trying to build, so in theory this should work:

```rb
class User
  attr_accessor :proc
end

FactoryGirl.define do
  factory :user do
    proc 'An attribute called proc'
  end
end

user = FactoryGirl.build(:user)
```

The expected behavior, I think, is that `user.proc` should now return `'An attribute called proc'`. It actually doesn't quite work that way. Instead `user.proc` returns `false`. I think this is a bug, probably coming from somewhere in `FactoryGirl::Evaluator`. I would be happy to fix this bug, although I don't expect doing so will make `rubocop` happy.

The simplest solution in this case may be to arrest `rubocop`.

**Comment by composerinteralia** [comment]
`self` where you are trying to define the `Proc` is an instance of `FactoryGirl::DefinitionProxy`:

```rb
FactoryGirl.define do
  factory :user do
    # Factory girl uses `instance_eval` to evaluate this block
    # in the context of a `FactoryGirl::DefinitionProxy` instance
  end
end
```

`FactoryGirl::DefinitionProxy` undefines all but a handful of [whitelisted methods](https://github.com/thoughtbot/factory_girl/blob/master/lib/factory_girl/definition_proxy.rb#L3), and neither `proc` or `lambda` make the cut. Undefining these methods keeps them from conflicting with attributes on the class you are trying to build, so in theory this should work:

```rb
class User
  attr_accessor :proc
end

FactoryGirl.define do
  factory :user do
    proc 'An attribute called proc'
  end
end

user = FactoryGirl.build(:user)
```

The simplest solution in this case may be to arrest rubocop.
