### ISSUE TITLE
Fails to recognize that attribute with block is an association

### ISSUE THREAD

**Issue by jaredbeck** [thoughtbot/factory_bot#1032]
In the following script, the `:fruit` factory works and the `:vegetable` factory does not. In our understanding of the DSL, we expect `association(:bowl)` to be the same as `bowl`.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.1.4"
  gem "factory_girl_rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foods, force: true do |t|
    t.string :species, null: false
    t.integer :bowl_id, null: false
  end

  create_table :bowls, force: true do |t|
    t.string :material, null: false
  end
end

class Food < ActiveRecord::Base
  belongs_to :bowl
end

class Bowl < ActiveRecord::Base
end

FactoryGirl.define do
  factory(:bowl) do
    material 'wood'
  end

  factory(:fruit, class: Food) do
    # Specifically saying `association` works.
    association(:bowl) { Bowl.create(material: 'copper') }
    species 'banana'
  end

  factory(:vegetable, class: Food) do
    # Not specifically saying `association` does not work.
    bowl { Bowl.create(material: 'copper') }
    species 'kale'
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal({ species: 'banana' }, FactoryGirl.attributes_for(:fruit))
    assert_equal({ species: 'kale' }, FactoryGirl.attributes_for(:vegetable))
  end
end
```

**Comment by joshuaclayton** [comment]
@jaredbeck howdy, and sorry for the confusion here!

You've actually stumbled across a couple of things here, one that could be handled better via code, and one that could be handled better via documentation.

From a code perspective, `association` isn't meant to accept a block (even though it does, and doesn't tell the developer!), and doesn't run the code within. You can verify this by inspecting material: `FactoryGirl.create(:fruit).bowl.material # "wood"` Arguably, `association` should raise and let the developer know they're using it in an unexpected way. I'd love to see a PR for that (with a test!), so if you're interested in contributing that, please do!

Secondly, `attributes_for` does nothing with associations (which it seems like you expect, given the two assertions); however, FG doesn't know that `bowl { }` is an association, since behind the scenes, it's only using those to build up a list of things to assign on an object, e.g.

```ruby
thing = Thing.new
thing.bowl = "" # return value of the block being executed
```

Apart from calling `save!` and a couple of things around `build_stubbed` not assigning a handful of attributes, it's basically ORM-agnostic. If you're looking to configure attributes on associations, [transient attributes](https://github.com/thoughtbot/factory_girl/blob/a22f256e5d938d9dc2b1d56ebdc497d73ce8fa45/GETTING_STARTED.md#transient-attributes) might help.

**Comment by jaredbeck** [comment]
> Arguably, association should raise and let the developer know they're using it in an unexpected way. I'd love to see a PR for that (with a test!), so if you're interested in contributing that, please do!

Sure, I'd be happy to work on that. Thanks for the quick response.

**Comment by sbleon** [comment]
I think the most confusing behavior, which I don't think we've addressed yet, is that `bowl` is correctly recognized as an association, but that `bowl { Bowl.create(...) }` is not recognized as an association. This behavior is surprising to the developer, at least it certainly surprised us yesterday (while I was working on troubleshooting and this issue report with Jared).

It looks like this code is the crux of the issue: https://github.com/thoughtbot/factory_girl/blob/master/lib/factory_girl/definition_proxy.rb#L96-L104. The presence of the block prevents the use of `Declaration::Implicit`, which is where the association would get recognized.

I don't see an easy way around this problem. The presence of the block makes the declaration "dynamic" instead of "implicit". Perhaps there could be a warning if a dynamic declaration used the same name as an existing factory, but I imagine that case is pretty common and we don't want to break people's code over this. Maybe just `attributes_for` could warn if there was such a "name collision"?

re: the docs update - One spot that needs updating is https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#dynamic-attributes. This doc tells the developer to use dynamic attributes for associations, which I think is confusing, because using a dynamic attribute prevents the automatic/implicit association-/factory-matching stuff from happening at all.

re: the `association`/block warning - I think that should go here: https://github.com/thoughtbot/factory_girl/blob/master/lib/factory_girl/definition_proxy.rb#L150-L152

**Comment by jaredbeck** [comment]
>> Arguably, association should raise and let the developer know they're using it in an unexpected way. I'd love to see a PR for that (with a test!), so if you're interested in contributing that, please do!

> Sure, I'd be happy to work on that. Thanks for the quick response.

PR https://github.com/thoughtbot/factory_girl/pull/1033 ready for review.

>> Secondly, attributes_for does nothing with associations  ..

So, if I understand correctly, 

Clarification 1: in the `:fruit` factory the `association` line **is effectively ignored** when we call `attributes_for`?

Clarification 2: In the `:vegetable` factory, the `bowl` line does not know, and **should not bother to know**, that `bowl` is an association?

If both of the above clarifications are correct, I can take a step at improving the docs, thanks.

**Comment by jaredbeck** [comment]
Closing via https://github.com/thoughtbot/factory_bot/pull/1033
