### ISSUE TITLE
Remove all instances of John Doe from the repository continued

### ISSUE THREAD

**Issue by Circuit8** [thoughtbot/factory_bot#1069]
Followed on from #1067 

@mjankowski Just posting this in a new issue because you blocked the other one. This is an open source project and this is a hotly debated issue, why stifle honest discussion about it? The decisions about the direction of the factory_girl gem affect all its users, and in the spirit of open source we really ought to be able to discuss those decisions on the repository.

> It's not so much a gendered name as it literally a name for a gender being assigned to something (a software library) which does not have a gender.

> We don't. They're pretty benign examples where something which has a gender is given a name commonly associated with one

You could say the same about the usage of a male gender with John Doe. The example user [does not necessarily have a gender](https://en.wikipedia.org/wiki/Genderqueer#Definitions_and_identity). Furthermore why is the default male?

> the name they are given is a pretty common pattern when you have a case of "I want to use a generic name here to make the point that it doesn't matter who the actual person is and this is just some stand-in data"

The usage of a gender based name for a project is also a pretty common pattern. eg. [Thor](https://github.com/erikhuda/thor), [Sinatra](https://github.com/sinatra/sinatra/), [Jekyll](https://github.com/jekyll/jekyll) etc. but that didn't stop us from renaming the gem.  So why the inconsistency?

**Comment by mjankowski** [comment]
You've been told on two different pull requests and two different issues that we are not going to accept this change. You've also been politely asked to move on from the topic multiple times, and continue to ignore that request.

Further pull requests for this change or new issues for this topic will be considered a sustained disruption to the project and result in your being blocked from the project.

Please move on.

**Comment by mxie** [comment]
First of all, thank you for your pull request. I appreciate your efforts to rid a project of all gender biases. It is awesome to see people in the open source community show that they too care about gender equality even in code.

A few more thoughts:

* Even though the name "John" is very commonly used for males, I don't think it's fair to say that someone whose name is "John" is inherently male. As you said, "the example user does not necessarily have a gender", so why make the assumption?

> The usage of a gender based name for a project is also a pretty common pattern. eg. Thor, Sinatra, Jekyll etc. but that didn't stop us from renaming the gem. So why the inconsistency?

* Just because something is a _pattern_, it doesn't make it ok. In fact, it's _because_ it is even a pattern to begin with that makes it all even more of a problem. That said, I strongly encourage you to open up an issue or PR for those projects if you'd like to see a change for social good.

* I think that another approach to your original PR could've been to ensure that more names in general were represented in our code _in addition to_ using gender neutral names. This would send a bigger message about equality and accepting people of all gender identities and expressions. Even though we're only talking about specs here, it's still important for people to feel that they are represented in the test database so that they can feel comfortable contributing to the project. Please consider the implications when you replace all instances of a single name with another single, alphanumeric name.

Again, thank you for your efforts.
