### ISSUE TITLE
specs for factories get loaded twice

### ISSUE THREAD

**Issue by BrianHicks** [thoughtbot/factory_bot#1122]
Hey! I'm trying to write a test for my factory. Specifically, for a factory tree I'm *re*writing to speed up.

This is how the relevant parts of my directory look:

```
spec
|- factories
   |- fast_user.rb
   |- fast_user_spec.rb
```

But when I run `bundle exec rspec spec/factories/fast_users_spec.rb`, the tests run twice. As far as I can tell, this is because:

1. RSpec finds the file
2. RSpec setup loads the factories
3. FactoryBot looks in `spec/factories` and loads all the `.rb` files, which defines the tests in that file again.

It's not like they're *slow* tests, but it'd be nice if FactoryBot knew about this pattern and didn't try to load `spec/factories/*_spec.rb`. I'm happy to make a patch for this change, if you're open to it. 😄

**Comment by joshuaclayton** [comment]
@BrianHicks fascinating! It makes sense that FB is picking these up, since it'll grab everything in `spec/factories`; I'd never considered that this directory could house `_spec.rb` files (that RSpec would subsequently *also* load).

In terms of the changes itself, in `FactoryBot` there's a `definition_file_paths` setting that points at particular *directories*, instead of individual files. I'm hesitant to omit files from there based on a particular pattern unless it was also configurable. An alternative (assuming we want to accommodate) might be to instead capture a list of filenames instead of a list of directories, which would allow developers to override that list (excluding `_spec.rb` files) themselves.

Other alternatives to `spec/factories_spec` might be `spec/integration` or `spec/harness`. I don't anticipate `spec/harness` to be too common, but `spec/integration` seems like it might be.

I know I threw a lot at you; any of this resonate or seem like a decent approach? I think my hesitation with having FB ignore certain suffixed files is that it might have a significant impact on existing codebases, and generally speaking I'm in favor of not modifying FB if I can avoid it 😃

**Comment by BrianHicks** [comment]
I found the relevant code in FB in the process of figuring out why this was happening. Your suggestion seems like a good idea, and isn't overwhelming so don't worry! I can think of three approaches for this API:

1. add `avoid_definition_files`, a list of strings which, if matched as a suffix, would not be loaded. (e.g. `spec/factories/user_spec.rb` is the suffix path of `/Users/brian/project/spec/factories/user_spec.rb`). Better name TBD, of course 😜
2. add `avoid_definition_file_patterns`, a list of regex patterns which, if matched at all, would not be loaded. (e.g. `.+_spec.rb$`)
3. add `select_definition_file`, either as a provided proc or a block argument to `FactoryBot.find_definitions`. This would act like `Array.select`. So:

   ```ruby
   FactoryBot.find_definitions { |path| !path.ends_with? "_spec.rb" }
   ```

All of these could preserve the current behavior by being empty lists or nil blocks. I like the third approach the best, but it'd require more documentation on how to integrate it properly into a Rails project.

What are your preferences here?

**Comment by joshuaclayton** [comment]
@BrianHicks Apologies on the slow reply; I've been mulling this over and the more I think about it, the more I think the factory specs themselves should live outside of `spec/factories/`. For the same reason one would avoid putting specs in `spec/support/`, `spec/factories/` (and `spec/factories.rb`) exists for the harness itself and not tests.

In terms of where they should instead live, I'm still not sure I have a good recommendation there. I can't recall anytime recently where I've tested a fake/mock, but I'd likely put factory specs in a similar place. `spec/integration` doesn't feel unreasonable to me.

**Comment by BrianHicks** [comment]
hmm, I can see where you're coming from. We currently have specs in `spec/harness`—your suggestion from before. It seems fine!

For the record, we also have `spec/factory_spec.rb`, which iterates over all of our factories and makes sure that they all meet a few basic criteria, like being valid without additional arguments. 

Anyway, it seems like the outcome is "we're not going to change factory bot to account for this use case". That's fine with me, and I'm grateful that you took the time to think about it. I'll close this issue for now, but of course you're welcome to reopen it if you think it's a use case for which you eventually want to solve. Thanks again!
