### ISSUE TITLE
Question: Are you open to new api for create_list ?? 

### ISSUE THREAD

**Issue by danielspaniel** [thoughtbot/factory_bot#1139]
I have been using create_list and find that it is way more useful to use it in more than just the way that you have now:

```ruby
create_list(:user, 2) # 2 users
create_list(:user, :trait1, 3) # 3 users
```
 
I want to propose a new way to use it like this:
```ruby
create_list(:user, :trait1, :trait2) # 2 users ( 1 with trait1 and the other with trait2
create_list(:user, :trait1, :trait2, :trait3) # 3 users ( 1 with trait1, the next with trait2, and the last with trait3 )
create_list(:user, [:trait1, name: 'Bob'],  :trait3) # 2 users 
```

You could still use create_list the old way .. I would just want to add the new style as well. 

This makes create_list super duper powerful and much more useful, and I can code the whole thing for you in a PR and whatnot, but want to make sure you are on board with the idea?

**Comment by joshuaclayton** [comment]
@danielspaniel I'd be hesitant to introduce an implied API in what could be covered by Ruby for the first couple of examples:

```ruby
%i(trait1 trait2 trait3).map {|trait| create(:user, trait) }
```

As for the final example, with traits + custom attributes, I'd be concerned it's not obvious what the intent is for each of those, so I might also lean on Ruby and some custom code to build a helper that uses it first. Generally speaking, I've approached FactoryBot's API such that it enables building blocks and extends the interface only when necessary, so custom construction and other approaches can be leveraged by developers dependent on each use-case. I think, at least with the first examples, iterating over an array of symbols and calling `create` directly is more approachable because it uses Ruby's `Enumerable` in a way developers can grok without needing to learn FactoryBot atop that.
