### ISSUE TITLE
Can't require rails_helper from custom PORO in factories directory

### ISSUE THREAD

**Issue by AdamT** [thoughtbot/factory_bot#1147]
I would like to create my own factories in my app. Not for creating fixtures but as a design pattern to sit next to other patterns such as `presenters`, `services`, `repositories`, etc..

I have 
```
app/
  factories/

spec/
  factories/
```

It is implemented like so:
spec/factories/troublemaker_factory_spec.rb:
```
require 'rails_helper`
RSpec.describe TroublemakerFactory do
...
end
```
When I bootup the server:
```
rails s
```

I get this backtrace:
https://gist.github.com/AdamT/ca4aad381e626e9fa53d2de65299eae8

Uninstalling FactoryBot from the Gemfile allows `rails s` to boot. I will probably rename my factories to `#{app_name}_#{model_name}_factory.rb` placed in `spec/"#{app_name}"_factories/` but thought others may like using their own factories as well.

Thank you for all the great work

**Comment by composerinteralia** [comment]
I see you are using `factory_bot_rails`. That gem adds a Railtie that finds any factories you have in `factories`, `test/factories`, or `spec/factories`: https://github.com/thoughtbot/factory_bot_rails/blob/master/lib/factory_bot_rails/railtie.rb

If you don't want that behavior and are not using the generators, I think you could use `factory_bot` instead of `factory_bot_rails`.
