### ISSUE TITLE
LoadError: `cannot load such file -- factory_girl`

### ISSUE THREAD

**Issue by spaghetticode** [thoughtbot/factory_bot#1204]
Since commit https://github.com/thoughtbot/factory_bot/commit/40eed88bb9222ee09001fbc7d301527836e0d085 I cannot use anymore `factory_bot` in order to test software depending on old versions of gems that, when released, depended on `factory_girl`. 

The error I'm getting is `LoadError: cannot load such file -- factory_girl`. 

I understand this is due to the gem renaming and side effects, I wonder if this is something that may be addressed in future versions of `factory_bot` or, when testing old code, `factory_bot` will need to be locked at commit https://github.com/thoughtbot/factory_bot/commit/f1f7719f6ebb3773656f2aa7a44fda1dd2530025 forever.

**Comment by spaghetticode** [comment]
@composerinteralia yes, they're open source, and new versions already replaced the `girl` gem with the `bot`.  So that's good.

But I also need to test that my extension works file with older versions of these gems, which may not be updated to use the `bot` easily.

**Comment by composerinteralia** [comment]
I tried out putting both factory_bot and factory_girl in a Gemfile, and it seems to work alright. That would be my recommendation if you need to use both versions in the same project. That should hopefully allow you to avoid locking to factory_bot 4.10.

I'm going to close this issue for now, since we aren't going to add back the deprecated factory_girl file to factory_bot.

Thanks!
