### ISSUE TITLE
rubocop-rspec AttributeDefinedStatically cop doesn't handle add_attribute

### ISSUE THREAD

**Issue by veganstraightedge** [thoughtbot/factory_bot#1241]
I get this deprecation warning. I run the suggested fix. Nothing changes. What am I reading wrongly in the message?

https://gist.github.com/veganstraightedge/c39efb0521e09fd0798a3e0323102732

Deprecation warning:

```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

alias { "orders" }

To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:

rubocop --require rubocop-rspec \
        --only FactoryBot/AttributeDefinedStatically \
        --auto-correct

(called from block (3 levels) in <top (required)> at .../spec/factories/foo_factory.rb:6) 
```

Code in question:

```ruby
FactoryBot.define do
  factory :foo do
    trait :from_orders do
      type { 'FROM' }
      attrs { {} }
      add_attribute :alias, 'orders'
    end
  end
end 
```

Thanks!

**Comment by composerinteralia** [comment]
Oh interesting. It looks like the rubocop-rspec `FactoryBot::AttributeDefinedStatically` Cop doesn't know how to deal static attributes defined with `add_attribute`. I didn't notice this before because I don't often need to use `add_attribute` directly, but I see why you would need it here.

I think we can open an issue on rubocop-rspec to correct `add_attribute :alias, 'orders', to `add_attribute(:alias) { 'orders' }`.

If you have any interest in looking into this, adding a test case to https://github.com/rubocop-hq/rubocop-rspec/blob/master/spec/rubocop/cop/rspec/factory_bot/attribute_defined_statically_spec.rb would be a good place to start.

**Comment by composerinteralia** [comment]
I'm going to go ahead and close this. We could potentially open an issue on rubocop-rspec, but given that at this point a critical mass has already gone through the upgrade I don't know if it would be worth the effort.
