### ISSUE TITLE
Should build_stubbed validate?

### ISSUE THREAD

**Issue by hmayer00** [thoughtbot/factory_bot#1295]
So, as I understand it `build_stubbed` is supposed to act like it was persisted to the database, to the extent feasible, without actually talking to the db. In other words mimic `create` as much as is feasible without incurring the database overhead.

If I'm understanding that correctly, I have a question: should `build_stubbed` validate the record? It seems like that would more closely mimic `create` (since invalid records wouldn't act like they were in the db) without incurring database-related overhead.

If you wanted to go down that road, it might need to be configurable (since introducing those validations might be problematic for folks who have been using `build_stubbed` without them). But I would argue that your tests will be better if the objects that act like they're persisted are validated along the way. If you're interested I can take a look at this in the next couple of weeks, but if my conception of `build_stubbed` is just different than yours then I can replicate that behavior as appropriate with callbacks.

**Comment by composerinteralia** [comment]
Thanks for the issue!

Did you have a specific problem with a `build_stubbed` record that was not valid? An example might help discuss whether this is something we should address.

My assumption is that, if you can successfully `create` a record with a given factory, the factory will also return valid records for `build_stubbed`. But I might be missing something.

Part of the reason to use `build_stubbed` is that it is faster. Adding validation steps could potentially slow `build_stubbed` down, so I wouldn't want to do that unless it solves a clear problem.

**Comment by hmayer00** [comment]
Well, in my specific case it was that I was setting up some initial state in a before_validation hook. (Though the wisdom of that is something I've since reconsidered). I was surprised to realize that the before_validation hook didn't run, since build_stubbed doesn't validate the record. So the initialized state that I was relying on happened if I did `FactoryBot.create`, but not with `FactoryBot.build_stubbed`.

But aside from the wisdom of that before_validation hook, it got me thinking about the fact that `FactoryBot.create` would throw an error if you fed it invalid attributes, but `FactoryBot.build_stubbed` would carry on without complaining. Personally, I think of `build_stubbed` as being `create` but without involving the DB. In which case I would expect it to validate, running before_validation hooks in the process. (Arguably it should even run before_save and before_create hooks as well, though I could see that differently, since those are potentially more likely to be database-related, and it really isn't going to save or create the record).

An example would be something like this:

```ruby
class Foo < ApplicationRecord
  validates :number, numericality: { greater_than: 2 }

  # ...
end

FactoryBot.define do
  factory :foo do
    number { 5 }
  end
end
```

So in this situation the base factory as written would create valid records, and would also build a valid record with build_stubbed. However, if you specified invalid attributes when calling the factory, the results diverge:

```ruby
FactoryBot.create(:foo, number: 1)
  # => ActiveRecord::RecordInvalid (Validation failed: Number must be greater than 2)
FactoryBot.build_stubbed(:foo, number: 1)
  # => #<Foo id: 1001, number: 0, ... >
```

I just wonder if `build_stubbed` should complain, so that it more closely mirrors what would happen if you were creating such a record. Of course I recognize that `build_stubbed` is in fact its own thing, and I shouldn't expect it be a complete drop-in for `create` (as has_many difficulties make clear). But I thought the conversation might be worth having.

**Comment by klyonrad** [comment]
There are probably very much examples in the real world where validations of models have to actually take a look in the database (accessing associated records with a scope for example), requiring some other data to be actually stored in the database.
I don't see how factory bot could magically stub every database accessing thight might happen in all the `before_validate` code that is out there.

Tests that are using `build_stubbed` often might not care about the validity of the object because the validations and what happens in the validate process is tested separately. So can't you just work around by running `.valid?` in an `after(:stub)` callback?

**Comment by joshuaclayton** [comment]
@hmayer00 your point about the validity of factories resonates, and why we'd introduced the ability to [lint factories](https://github.com/thoughtbot/factory_bot/blob/b20b58b91ef3838002f9c2490bbb68b733281231/GETTING_STARTED.md#linting-factories). By default, the linter uses the "create" strategy, which means validations should run; by adding a Rake task (the example source of which can be found in that section), that should address concerns around invalid factories existing in the first place.

This *doesn't* actually address your point about validations and other hooks being called via `build_stubbed` – the original use case (IIRC) was for view specs. Historically, we've avoided setting attribute values/mutating state (independent of AR internals) in callbacks due to issues with testing; for both of those reasons, `build_stubbed` focuses more on some of the "more obvious" pieces of DB persistence (presence of the primary key, created_at/updated_at).

Given the complexity around validations/callbacks and ensuring we're not interacting with the database, I don't think FB can ever capture *every* interaction, and callbacks (at the AR/ORM/ODM level) is likely one set of those interactions.

**Comment by hmayer00** [comment]
@joshuaclayton that all makes sense, and btw I love the linter, and have been happily using it since I learned about it! And I agree that making sure your base factories create valid objects solves most of the problem. The issue that remains for me is that even if the _base_ factory is just fine, you can still `build_stubbed` a factory with an attribute that makes it invalid, and nothing will complain, even though if you ran `create` with the same factory it would choke.

That said, this issue was phrased as a question intentionally, and I think you've answered it in the negative - `build_stubbed` should not validate, and there are good reasons why not (both for performance reasons and it just being out of scope). So that all makes sense, and while I'd love for there to be a solution that prevented `build_stubbed` from giving you back an object that couldn't exist in the db, I really don't see an option that doesn't suffer from the drawbacks you've mentioned. So I'm gonna go ahead and close this issue, since I think it's been answered. Thanks for the time!

Also @klyonrad, fair point about the (common) database interactions of validation. And yes, one could certainly force the validation in an `after(:stub)` if one wanted to do so. That would solve the initial problem of needing something to happen in a before_validation hook, though as I mentioned I eventually thought better of that whole mechanism. For me it ended up being more about realizing that I should be a bit more careful with `build_stubbed` than I had been thinking. I'm entirely used to the idea that sometimes `build_stubbed` will fail when `create` would pass - of course some things just need to talk to an actual database! But what I hadn't realized was that the reverse was also true, and you could end up in the less-obvious situation where `build_stubbed` would pass while `create` would fail, because you didn't realize you were operating on fundamentally invalid objects. It's totally fine and something I will keep in mind (at least until I forget all about it). But it's just something I hadn't thought about before.

Anyway, good talk. Thanks all!
