### ISSUE TITLE
How can I batch updates to the created object before returning it?

### ISSUE THREAD

**Issue by mikesnare** [thoughtbot/factory_bot#1360]
Imagine this factory:

```ruby
FactoryBot.define do
  factory :main_model

  trait :with_a do
    after(:create) do |main_model|
      # Both sides refer to each other, so this must be done in after(:create).
      main_model.update(a_id: create(:a, main_model_id: main_model.id).id)
    end
  end

  trait :with_b do
    after(:create) do |main_model|
      # Both sides refer to each other, so this must be done in after(:create).
      main_model.update(b_id: create(:b, main_model_id: main_model.id).id)
    end
  end
end
```

Note that we are not using ActiveRecord so we can't use any of the normal association support.  We must do this manually.  But, the associations are effectively `has_one` and `belongs_to` so that the association is recorded on both sides.  This means that we cannot create the associated objects (`A` and `B`) until the `MainModel` is created and we have the main models's instance ID, and we then need to update the `MainModel` after creating _each_ of the associations.

The result of a call to `create(:main_model, :with_a, :with_b)`, then, is the following:

1. create the main model
2. create the A class
3. **update the main model**
4. create the B class
5. **update the main model**

What I would like to do is combine steps 3 and 5 into a single update that runs right before the main model that was created in step 1 is finally returned to the caller.  In this example, it only saves one write, but some specs use many more traits, and we have dozens of thousands of specs, so the savings would not be meaningless.

I cannot figure out how to achieve this.  Any suggestions?

(I first asked on [StackOverflow](https://stackoverflow.com/questions/59375930/how-to-achieve-update-batching-in-factorybot-for-traits) but wasn't able to get a working solution).

**Comment by composerinteralia** [comment]
You might be able to get something working with transients:

```rb
require 'factory_bot'

class Thing
  attr_accessor :a, :b
end

FactoryBot.define do
  factory :thing do
    transient do
      should_build_a {false}
      should_build_b {false}
    end

    trait :with_a do
      transient do
        should_build_a {true}
      end
    end

    trait :with_b do
      transient do
        should_build_b {true}
      end
    end

    after(:build) do |thing, evaluator|
      thing.a = "A" if evaluator.should_build_a
      thing.b = "B" if evaluator.should_build_b
    end
  end
end
```

**Comment by composerinteralia** [comment]
Ah, I see now it looks like people mentioned transients on Stack Overflow as well.

Another option might be to write some helper methods that create the objects with factory_bot, but then do the updating as a separate step outside of factory bot:

```rb
def main_with_a_and_b
  main = create(:main)
  a = create(:a, main: main)
  b = create(:b, main: main)
  main.update!(a: a, b: b)
end
```

I tend to prefer this second approach where possible, since it keeps the factories simpler.

**Comment by mikesnare** [comment]
I'd trade a complex factory for simpler specs any day.  😄

Basically I think what I'm looking for is a `before(:return)` callback that is invoked right before the factory returns the final object.  Just a way to do last-minute "stuff".  I can think of any number of ways to track that "stuff" needs to be done, there's just no hook point to do it in.

**Comment by composerinteralia** [comment]
> I'd trade a complex factory for simpler specs any day. 😄

The approach with a helper method could still keeps your specs simple. The helper method might live somewhere in spec/support, and the the spec itself would have something like `main = main_with_a_and_b` (rather than `main = create(:main, :with_a, :with_b)`).

> callback that is invoked right before the factory returns the final object.

That is what the [`create` callback](https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/strategy/create.rb) already does. Triggering that callback is last thing that happens when using the `create` strategy.

**Comment by mikesnare** [comment]
> The helper method might live somewhere in spec/support, and the the spec itself would have something like main = main_with_a_and_b (rather than main = create(:main, :with_a, :with_b)).

That would certainly work, but I don't want to have to create cover methods for each combination of main object and association that I might want.  I'd much prefer this to be something that "just works" in the factory so that I don't have to write the factories and associations and _then_ go back and write the extra methods that people need to call when they need some arbitrary combination.

> That is what the create callback already does. Triggering that callback is last thing that happens when using the create strategy.

... on a per-factory/trait case.  The `after(:create)` callback for the main factory runs before the `after(:create)` for each trait.  I can't write the association ids into the main model in the main factory's `after(:create)` because they haven't been created yet.  I can't use `after(:build)` for any of this to change the order because the point is to have IDs.

There is no single point at the **_very end_** of the factory run that could do anything with the object that is about to be returned.  It's exactly that that I think I need.

**Comment by composerinteralia** [comment]
> There is no single point at the very end of the factory run that could do anything with the object that is about to be returned. It's exactly that that I think I need.

When using the `create` strategy, the `after(:create)` callback is the absolute last thing that happens.

> I don't want to have to create cover methods for each combination

In that case transients are the only solution I can see within factory_bot itself.

You might also consider a function that takes an argument to determine which associations to build. Something like:

```rb
def create_main(overrides: {}, associations: [])
  main = create(:main, **overrides)
  associations.each do |association|
    main.public_send("#{association}=", create(association, main: main))
  end
  main.tap(&:save!)
end

create_main(associations: [:a, :b])
```

This might be a bit on the clever side, but I think it is still clearer than fighting your way through doing this with factory_bot callbacks.

---

It is possible that this is related to some of the issues we have around better support for collection associations (https://github.com/thoughtbot/factory_bot/issues/458 is the placeholder for those). The challenge with those issues (and I think this one as well) is that factory_bot was designed to create valid objects for tests, one object at a time; it was not designed to create custom, complex networks of objects. I think helper functions are more effective for building these relationships that tend to me more specific to each individual application.

I am going to close this issue for now because I don't see a clear way to make what you are trying to do easier in factory_bot itself, and I also think it is a bit outside the scope of what factory_bot is designed to do.

Thanks for opening the issue. It has been interesting to think through.
