### ISSUE TITLE
factory bot fails with undefined method when used with  Mongoid::Attributes::Dynamic

### ISSUE THREAD

**Issue by kp666** [thoughtbot/factory_bot#1368]
### Steps to reproduce
Using dynamic fields in mongoid and creating a factory, fails with an undefined method error.
If I use fields instead of dynamic attributes, it works. As far as I debugged, mongoid uses method missing to have dynamic attributes.

[reproduction script]: 

https://gist.github.com/kp666/18a059e1f3f592a6d5e00fabbd466944
  undefined method `some_field' for #<User:0x00007ffff54e6680>
### Expected behavior
Should create some_field

### Actual behavior
Fails with undefined method "some_field="

### System configuration
**factory_bot version**:  5.1.1
**rails version**:   6.0.0
**ruby version**:  ruby-2.7.0

**Comment by composerinteralia** [comment]
Thanks for the issue!

I don't know much about mongoid, but I can tell you that with your example factory running

```rb
FactoryBot.create(:failing_user, some_field: SecureRandom.random_number(1000))
```

is equivalent to running:

```rb
user = User.new
user.some_field = SecureRandom.random_number(1000)
user.save!
```

So as a first step I would try running those lines by themselves. If they produce the same error, then the problem is not coming from factory_bot.

If that doesn't help, reproducing the error in a runnable script along the same lines as our example [ActiveRecord reproduction script](https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb) would be helpful. Otherwise I wouldn't know quite how to reproduce this given my limited knowledge of mongoid.

**Comment by kp666** [comment]
Seems not to be a factory_bot issue then

https://gist.github.com/kp666/4670e5867554af1a3a8db0a6949785bd
