### ISSUE TITLE
Transient variables can't be passed to association factory

### ISSUE THREAD

**Issue by softwaregravy** [thoughtbot/factory_bot#1391]
### Description

Trying to pass transient values to association factories

### Reproduction Steps
https://gist.github.com/softwaregravy/be7f9bfd32154f72fa571408a499b480

### Expected behavior

I think the gist I attached should work

### Actual behavior

```
1) Error:
FactoryBotTest#test_comment:
KeyError: Trait not registered: "extra_body"
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/activesupport-6.0.2.2/lib/active_support/hash_with_indifferent_access.rb:191:in `fetch'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/activesupport-6.0.2.2/lib/active_support/hash_with_indifferent_access.rb:191:in `fetch'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/registry.rb:23:in `find'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/decorator.rb:10:in `method_missing'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/internal.rb:44:in `trait_by_name'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition.rb:114:in `trait_by_name'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition.rb:106:in `block in base_traits'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition.rb:106:in `map'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition.rb:106:in `base_traits'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition.rb:133:in `aggregate_from_traits_and_self'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition.rb:34:in `to_create'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/definition_hierarchy.rb:6:in `build_from_definition'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/factory.rb:125:in `build_hierarchy'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/factory.rb:88:in `compile'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/factory_runner.rb:14:in `run'
    /Users/johnhinnegan/.rvm/gems/ruby-2.6.5@factory_bot_repro/gems/factory_bot-5.2.0/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
    quick_repo.rb:71:in `test_comment'
```

### System configuration
**factory_bot version**:  
**rails version**:  
**ruby version**: 2.6.5

https://github.com/softwaregravy/factory_bot_repro

**Comment by composerinteralia** [comment]
Thanks for the issue. It is expected behavior that the gist you provided does not work, although I suspect we could improve the error message a bit along the lines of what we did in https://github.com/thoughtbot/factory_bot/pull/1286.

When you write `extra_body` inside the factory definition you aren't referring to the transient attribute with that name. Instead, since you are still in the scope of the factory definition, that defines in implicit declaration (implicit declarations can be [associations](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#implicit-definition), [sequences](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#as-implicit-attributes), or [traits](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#as-implicit-attributes-1), depending on the context). Passing an implicit declaration as a factory attribute is probably not something anybody wants to do, so I think that we should try to raise a helpful error.

Passing a transient attribute along to an association is possible, but you would need to enclose it in a block to have access to the attribute:

```rb
parent_entity { association(:post_extra, extra_body: extra_body) }
```

This syntax has not yet made it to the documentation, but there is a PR open for that: https://github.com/thoughtbot/factory_bot/pull/1353.

**Comment by softwaregravy** [comment]
Awesome, thank you for the detailed explanation.
