### ISSUE TITLE
Factory for model with attribute named 'y' breaks console reload! 

### ISSUE THREAD

**Issue by rounders** [thoughtbot/factory_bot#1397]
### Description

If you have a rails model with an attribute named 'y' and you have a factory that sets this attribute, then using the reload! command in the rails console generates the following error:

```
NoMethodError (undefined method `end_line=' for nil:NilClass)
```

### Reproduction Steps

1. create a new rails 6.0.x project
2. add factory_bot_rails to gemfile & bundle install 
3. create a rails active record model which includes an attribute named 'y' (eg rails g model Foo name:string x:float y:float and then run rails db:migrate  )
4. start the rails console and enter the reload! command in the console 

### Expected behavior

the Rails console should reload the application

### Actual behavior

the following error message is displayed:
```NoMethodError (undefined method `end_line=' for nil:NilClass)```

If you comment out the line in the factory definition that sets 'y', then you will not encounter an error message when using the console reload! command

### System configuration
**factory_bot_rails version**:  5.2.0
**factory_bot version**:  5.2.0
**rails version**:  6.0.3
**ruby version**: 2.5.5 (also tested with 2.6.3 with same results)

### Additional Information

It happens during the FactoryBot.find_definitions call, though ultimately the error message occurs in psych's tree_builder.rb file but I wasn't able to track down why.

**Comment by rounders** [comment]
@composerinteralia thanks for the workaround, that does indeed do the trick!

**Comment by composerinteralia** [comment]
I played around with #1144 a bit more, and I don't see a way of making it work without potentially breaking the code of anyone who is extending the definition proxy (`BasicObject`s don't have an `#extend` instance method). Since we don't offer an alternative way to extend factory_bot with additional methods, this is not something I want to mess around with at the moment.

Since I think this is a fairly uncommon edge case, and there is a reasonable workaround, I am going to close this issue for now. If the issue comes up again I will reconsider.

Thanks for opening! This was an interesting one.

**Comment by jshow** [comment]
I just bumped into this - your solution works, a small bit of debt I'll document. thank you

**Comment by joshuapinter** [comment]
Ha! This is exactly what it is. Good sleuthing! I was trying to figure out what was special about these factories that it was causing this exception. 

Definitely not an ideal fix but a minor eyesore to work around what should be a fairly rare issue. 

Thanks!

**Comment by krtschmr** [comment]
@composerinteralia works perfect with `add_attribute` 💪🏿
