### ISSUE TITLE
build_stubbed vs build performance and preference in usage

### ISSUE THREAD

**Issue by bekasovoleg** [thoughtbot/factory_bot#1439]
`FactoryBot` are used with option `FactoryBot.use_parent_strategy = true`
 Which one `build_stubbed` or `build` is it preferable to use and why?
Are there any proofs `build_stubbed` is faster than `build` or vise versa?

**Comment by composerinteralia** [comment]
`build` will initialize your object, but will not save it. `build_stubbed` is similar but does some extra work to ensure that you don't call any [methods that hit the database](https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/strategy/stub.rb#L6-L25).

`build_stubbed` is going to be a tiny bit slower because of the extra work it has to do, but you can be more confident you wont accidentally hit the database (which is _really_ slow).
