### ISSUE TITLE
Overwrite implicitly defined mirrored associations with self by default

### ISSUE THREAD

**Issue by rjclaasen** [thoughtbot/factory_bot#1524]
Thank you all for your work on this project. It's been simply amazing to work with!

### Problem this feature will solve

Let's say I have two models with a one-to-one association between them. I want to have factories for each of them, and, by default, fill in these associations as well. Creating either factory should create one instance of both models.

### Desired solution

I would love to be able to do that in the following manner:

```ruby
factory :user do
  comment
end

factory :comment do
  user
end
```

In this case, when calling `FactoryBot.create(:user)`, I expect one user and one comment associated with each other to be created. When FactoryBot calls the comment factory from the user factory, it should fill in the `user` field with the user that is already being built. Then:

```ruby
FactoryBot.create(:user) # Should create one user and one associated comment
# Instead, each factory keeps calling the other in an infinite loop of association building.
```

## Alternatives considered

This can be achieved in the current version by doing:

```ruby
factory :user do
  comment { association :comment, user: instance }
end

factory :comment do
  user { association :user, comment: instance }
end
```

but that is quite verbose and a little less readable (in my opinion).

## Additional context

I am not the most proficient with FactoryBot or Rails in general, so please let me know if there are any alternative solutions!

Feedback & your other thoughts are also very welcome.

Thanks again for all of your work!

**Comment by aledustet** [comment]
Thanks for the kind words @rjclaasen in the name of everyone that has contributed to factory bot. From a rough read of the associations creation process(lib/factory_bot/declaration/association.rb) in order to address this issue, I would say we could check if the invoking factory has an association to the current factory and then access the instance before creating a new value. But in order to do that we couldn't stop at one "level" deep of the declaration, it could go a few layers deep easily. This sounds like a graph traversal to find a cycle to me and seems like overkill to run it every-time an association is created. The example you provided is a similar to the one expressed [here](https://stevepolito.design/blog/create-dependent-associations-in-factorybot/) but take a look at the warning:

```
Note that this approach works with build, build_stubbed, and create,
but the associations will return nil when using attributes_for.

Also, note that if you assign any attributes inside a custom initialize_with 
(e.g. initialize_with { new(**attributes) }), those attributes should not refer 
to instance, since it will be nil.
```

To decide which value to pick by default might get hairy because the invoking factory would be dictating what value to use here, and overrides once the nesting(one factory calls another ...) gets going I don't really know if there's a clear way to get there.

There are other strategies using [transient attributes](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#transient-attributes) that will give you better control on the lifecycle of the attributes that are added. You can find examples on how to use transients here and also a more intricate example with associations on [this post](https://stevepolito.design/blog/create-dependent-associations-in-factorybot/) I hope this gives you an idea of some alternatives. If you can illustrate other use cases for a change of behavior on how we create associations, please use the repro script on the repo, and if you are so kind please elaborate on how the change on API would impact other associations. Thanks.

**Comment by aledustet** [comment]
@rjclaasen have you tried any of the alternatives? Would you say that any of them addresses your concern?

**Comment by rjclaasen** [comment]
I have chosen to use the verbose alternative as specified in the original post.

Thanks for all the help!
