### ISSUE TITLE
An attributes_for method that builds associations and also returns their ID's

### ISSUE THREAD

**Issue by jmuheim** [thoughtbot/factory_bot#408]
In a controller spec of a Rails 3 app, I'd like to have an easy way to populate the `valid_attributes` method with the help of FactoryGirl.

Sadly, `attributes_for` does not create needed associations, while `(FactoryGirl.build :position).attributes.symbolize_keys` returns too much stuff (e.g. timestamps which may not be available for mass assignment). So here's my solution:

```
(FactoryGirl.build :position).attributes.symbolize_keys.reject { |key, value| !Position.attr_accessible[:default].collect { |attribute| attribute.to_sym }.include?(key) }
```

It would be nice, though, to have a method built right into FG which provides this functionality.

**Comment by goulvench** [comment]
I had the same issue as the OP, my colleague @PKoin suggests the following syntax:

```
FactoryGirl.create(:object_with_associations).attributes.except('id', 'created_at', 'updated_at')
```
After running this, the object is created, all factory associations are built, and the returned hash contains all attributes of the object, including the foreign key for each association. To get the keys as symbols instead of strings, one simply needs to add `.symbolize_keys` at the end.

--- 
Pros: it works!
Cons: blacklisting attributes can be tedious
