### ISSUE TITLE
Factories for database views

### ISSUE THREAD

**Issue by jacob-carlborg** [thoughtbot/factory_bot#449]
We have a bunch of database views in our Rails application that aggregates data from several other tables. Is it possible to have factories for these views, somehow?

The problem is that it's not possible to insert new rows in a view. I need to somehow insert the rows in the underlying tables instead.

**Comment by amnesia7** [comment]
@joshuaclayton 
My setup is `users` have many `projects` and `projects` have many `tasks`. 
I have merged these together using a database view (with a `project_task` model) but I have cherry-picked the fields in the database view that I want to include rather than including all fields from each of the 3 models.
My current factories are:
```
factory :user do
  # user fields
end

factory :project do
  # project fields
  user
  tasks       { [association(:task)] }
end

factory :task do
  # task fields
end
```
In my specs I currently need to do:
```
before do
  @user = create(:user)
  @project = create(:project, user: @user)
  @project_task = ProjectTask.first
end
```
Is there a way to create a factory for this setup?
