### ISSUE TITLE
FactoryGirl doesn't handle array: true

### ISSUE THREAD

**Issue by catilac** [thoughtbot/factory_bot#480]
I'm using PG array columns, specifically, a string array. FactoryGirl treats this column as a regular string.

Am I doing something wrong? Or is this something that I can fix in FactoryGirl?

Either way, can someone point me in the right direction?

Thanks!

**Comment by slothbear** [comment]
`rake db:test:prepare` did the trick for me.

I added an array column to my table with `default: []`  The tests could see the column, but the default was nil. I added a line to my factory to set the value to a new array, but it was interpreted as the string `[]` instead of an array.

After `rake db:test:prepare`, the default empty array is recognized, and I didn't need to change the factory. Just recording here in case someone else sees this pattern. Thanks for the tip!
