### ISSUE TITLE
ActiveRecord::RecordInvalid:Validation

### ISSUE THREAD

**Issue by lellisga** [thoughtbot/factory_bot#523]
I'm currently working in a project that uses test seeds and factories, this is causing FactoryGirl to raise an  `ActiveRecord::RecordInvalid:Validation failed: [Object] has already been taken`. It seems like factory girl is expecting to have an empty database. This doesn't make sense to me since it should follow a sequence. Any thoughts?

The way that i'm solving this issue is by using the following statement:

![screen shot 2013-05-09 at 10 39 06 am](https://f.cloud.github.com/assets/210771/483463/9f7b53fe-b8be-11e2-981a-933128d82624.png)

``` ruby
begin
  factory = Factory.create(:name) rescue retry
end

# or

begin
  factory = Factory.create(:name) rescue ActiveRecord::RecordInvalid retry
end
```

If this is a valid issue I can start to work over the solution.

**Comment by AnwarShah** [comment]
@joshuaclayton This is still an issue. I don't how to overcome this? Need a decent solution.

**Comment by joshuaclayton** [comment]
@AnwarShah what have you tried? What's the issue?

My recommendation is to get comfortable with the non-FG solution, and then layer in FG. More often than not, issues in tests are less about how FG behaves and more about the test setup and execution. Check out the bottom paragraph of [this wiki page](https://github.com/thoughtbot/factory_girl/wiki/How-factory_girl-interacts-with-ActiveRecord).

**Comment by AnwarShah** [comment]
@joshuaclayton Thank you for paying attention to this issue. But in my case, it's how FG behaves in case of uniqueness validations. The documentation should be clearer in my opinion. 

For example, I have a `Department` model which has a uniqueness validation on name. Now, When I used this association on a `Course` table in FG-factory, it would raise exception due to violation of uniqueness validation, This happens when you need to create two course for example. There should be an easier way to avoid this.

I finally used 

```
initialize_with { Department.find_or_create_by(name: 'UniqueNameHere') }
```
to avoid this. However, it's too painful if I creating a department requires too many attributes.

**Comment by joshuaclayton** [comment]
@AnwarShah if there's documentation that's confusing, I'd be happy to look at a PR. I'm still having an issue understanding the actual modeling case where this is necessary.
