### ISSUE TITLE
Is it possible to include a trait by default in a factory?

### ISSUE THREAD

**Issue by chintanparikh** [thoughtbot/factory_bot#528]
Consider this factory:

```
# Read about factories at http://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :follow_up do
    first_name      { Faker::Name.first_name }
    last_name       { Faker::Name.last_name }
    phone           { Faker::PhoneNumber.cell_phone.gsub(/[^\d]/, '').gsub(/^1/, '2')[0..9] }
    email           { Faker::Internet.email }
    email_preferred true
    consent         false

    trait :by_referral do
      association :hospital
      association :referral
      source { FollowUp::REFERRAL}
    end

    trait :by_provider do
      association :provider
      source { FollowUp::PROVIDER }
    end
  end
end

```

I want to either default to include the by_referral trait, or the by_provider trait. It shouldn't be valid if neither trait is included. Is this possible, or is there a better way to do this?

**Comment by ChrisBAshton** [comment]
In case anybody else comes across the same issue as me - you cannot have a default trait which has the same name as an existing factory. See https://github.com/alphagov/content-publisher/pull/1568#discussion_r362202799 for full context.

Instead of

```ruby
image

trait :image do
  # etc
end
```

...I had to rename to:

```ruby
for_image

trait :for_image do
  # etc
end
```

...as I already had an `:image` factory elsewhere in the repository.

This nuance is captured in the [getting started guide](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md): "Note that defining traits as implicit attributes will not work if you have a factory or sequence with the same name as the trait" - but is easy to miss if you are skimming.
