### ISSUE TITLE
after(:build) callback should be triggered prior to save

### ISSUE THREAD

**Issue by rymohr** [thoughtbot/factory_bot#649]
Perhaps I'm misusing the callbacks, but shouldn't the `after(:build)` callback allow you to finalize associations and attributes prior to saving?

I have a block I want to run regardless of whether `build` or `create` is used.  Here's a simplified example:

```
factory :account do
  ignore do
    locked false
  end

  after(:build) do |account, options|
    account.user ||= build(:user)
    account.user.status = :unpaid if options.locked
  end
end
```

If I call `FactoryGirl.create(:account, :locked => true)` it tries to save the account before the `:build` callback is ever triggered.

**Comment by lsantobuono** [comment]
Hi guys sory for bringing this up, facing this same issue.
I need the association to be created before the after_save callbacks are called, because one of those uses the associations to make an operation. This works fine within a controller with nested attributes.
Is there any way to simulate the behaviour while testing?
thanks in advance.
