### ISSUE TITLE
v4.7.0 introduces instance variables that do not play well with ActiveSupport's to_json

### ISSUE THREAD

**Issue by shepmaster** [thoughtbot/factory_bot#941]
Starting in  6f7b94b159078dcf0a4c832e42ffc256f90e5253 and released in 4.7.0, the `ActiveModelDirtyBackport` module is injected into classes that don't respond to `clear_changes_information`. As suggested by the name, this covers classes that have nothing to do with ActiveModel.

Unfortunately, this conflicts with ActiveSupport's implementation of `as_json` / `to_json`, as it [falls back to using all the instance variables](https://github.com/rails/rails/blob/v5.0.0.1/activesupport/lib/active_support/core_ext/object/json.rb#L48-L54).

This demo should help explain:

``` ruby
require 'factory_girl'

require 'active_support/core_ext/object/json'
require 'active_support/hash_with_indifferent_access'
require 'active_support/json'

class Customer
  attr_accessor :id
end

FactoryGirl.define do
  factory :customer
end

customer = FactoryGirl.build_stubbed(:customer)
puts customer.to_json
# => {"id":1001,"previously_changed":{},"changed_attributes":{}}

customer = Customer.new
puts customer.to_json
# => {}
```

When constructed through factory_girl, the unexpected attributes `previously_changed` and `changed_attributes` now show up.

**Comment by shepmaster** [comment]
One workaround is to explicitly ignore these attributes when generating JSON. This only really makes sense when directly doing so in a test, and not scattering this throughout the production code.

```ruby
foo.as_json(except: ['previously_changed', 'changed_attributes'])
```

**Comment by joshuaclayton** [comment]
@shepmaster that's... frustrating. I can see the line of reasoning that makes instance variables seem appealing as an implementation for `#to_json`, but in this case, I see your point that it's causing problems.

Seems like it might be better to override the offending method with the behavior you want instead of managing a list of attributes you don't, e.g. defining `to_json` on your object and exposing only what you want on the class?

**Comment by shepmaster** [comment]
> e.g. defining to_json on your object

Could be a reasonable solution for some people, but in this case it's a third-party class from a gem. When they (and most people?) designed their class, I assume they believed they'd be in control of which instance variables would be present in their own class, thus saying "all instance variables" is reasonable.

Is there a way to disable the monkey-patched dirty tracking for a given class / factory?

**Comment by joshuaclayton** [comment]
> Could be a reasonable solution for some people, but in this case it's a third-party class from a gem. When they (and most people?) designed their class, I assume they believed they'd be in control of which instance variables would be present in their own class, thus saying "all instance variables" is reasonable.

Excellent point, I hadn't thought about that. I was operating under the assumption the factory was for something the developer controls and not an external library.

> Is there a way to disable the monkey-patched dirty tracking for a given class / factory?

Currently, now. @quadule, do you have any thoughts here having dug through some of the intricacies of the dirty handling? Since this is dependent on ActiveModel, I wonder if we can look at the object's ancestors (versus checking to see if it responds to `#dirty?`, whose interface could be present but not come from ActiveModel) and conditionally include based on that as well?

**Comment by sgrif** [comment]
This seems like the simplest solution:

```ruby
def clear_changes_information
  if defined?(@previously_changed) && defined?(@changed_attributes)
    @previously_changed = ActiveSupport::HashWithIndifferentAccess.new
    @changed_attributes = ActiveSupport::HashWithIndifferentAccess.new
  end
end
```

**Comment by quadule** [comment]
I'm a little unclear on the purpose of using `build_stubbed` on something besides an ActiveRecord model, but if that should be supported then @sgrif's solution looks good.

It could check for ActiveModel::Dirty ancestry instead, but the stub strategy doesn't check for ActiveRecord ancestry before stubbing the persistence methods.

```ruby
clear_changed_attributes_on_result(instance) if instance.kind_of?(ActiveModel::Dirty)
```
