### ISSUE TITLE
FactoryGirl.modify appears broken

### ISSUE THREAD

**Issue by rob-anderson** [thoughtbot/factory_bot#969]
I feel like I am missing something obvious but see below:

irb

> irb(main):001:0> require 'factory_girl'
> => true
> irb(main):002:0> FactoryGirl::VERSION
> => "4.7.0"
> irb(main):003:0> class User; attr_accessor :name; end
> => nil
> irb(main):004:0> FactoryGirl.define do
> irb(main):005:1* factory :user do
> irb(main):006:2* name 'foo'
> irb(main):007:2> end
> irb(main):008:1> end
> => []
> irb(main):009:0> FactoryGirl.build(:user)
> => #<User:0x007ff195007448 @name="foo">
> irb(main):010:0> FactoryGirl.modify do
> irb(main):011:1* factory :user do
> irb(main):012:2* name 'bar'
> irb(main):013:2> end
> irb(main):014:1> end
> => #<FactoryGirl::Declaration::Static:0x007ff1939cb058 @name=:name, @ignored=false, @value="bar">
> irb(main):015:0> FactoryGirl.build(:user)
> => #<User:0x007ff1939b8868 @name="foo">

So why is the factory stuck on name 'foo'?

**Comment by rob-anderson** [comment]
OK figured it out.

It looks like it's not possible to modify a factory after it has been used once.

Not sure if this is by design but the behaviour was the same right back to 4.4.0.

I'd close the issue but I'll leave it open with the suggestion that this might merit an extra sentence in the relevant section of GETTING_STARTED.md

Thanks for maintaining this very useful gem.

**Comment by jrochkind** [comment]
hmm, I'm having trouble with FG.modify too, in FG 4.7.0, my 'modify' directives don't seem to have any effect. 

I wouldn't have thought I had used it even once before `modify`, but @rob-anderson's hint gives me something to look for at least, I'll try to figure out how to put breakpoints in to ensure it hadn't been used before. If it had been used before, it will have been in some weird way that's probably hard to eliminate. 

@rob-anderson, you're saying this has been true since 4.4.0?  Hmm, looks like my app prior to upgrading was using 4.5.0, and having no trouble. 

Okay, got to try to get to the bottom of what's causing my problem, may or may not be "can't modify factory already used".  (But if modify on a factory that's already been used is a no-op -- I'd rather have it raise than be a no-op!)

**Comment by jrochkind** [comment]
Okay, I haven't managed to figure out if the factory I'm trying to `modify` had already been used once first. 

But I have determined that:

  * With FG 4.5.0, my `modify` in my actually existing app works again -- no changes to app except FG/FG-rails version. And you indeed still can't modify a factory that's already been used. So something else changed. 

* With FG 4.7.0, my `modify` (of a factory from a gem) has no effect at all, it's like it was a total no-op. 

I was going to test in FG 4.6.0, but it seems not to exist! 

So something has indeed changed between 4.5.0 and 4.7.0 to make `modify` stop working. I am not quite sure how to dig into what to debug. 

For now I guess I'll pin to 4.5.0 so my tests keep working.

**Comment by jrochkind** [comment]
ugh now I can't reproduce anymore either I may have just gotten confused too myself. 

Still suggest that if in any cases (like factory has already been used) FactoryGirl.modify is going to be a no-op -- it should raise, indicating it couldn't do what was asked of it, instead of just silently no-oping.

**Comment by joshuaclayton** [comment]
@jrochkind thanks for clarifying here - I've closed the issue for now, but if you run into things moving forward, don't hesitate to reopen this.
